version: '3.8'

services:
  iol-calculator:
    build: .
    container_name: iol-calculator-api
    ports:
      - "5000:5000"
    volumes:
      - ./screenshots:/app/screenshots
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s